rootProject.name = "gof-patterns-java"

include("factory-method")
include("abstract-factory")
include("singleton")
include("builder")
include("prototype")
include("adapter")
include("bridge")
include("composite")
include("decorator")
include("facade")
include("flyweight")
include("proxy")
include("chain-of-responsibility")
include("command")
include("iterator")
include("mediator")
include("memento")
include("observer")
include("state")
include("strategy")
include("template-method")
include("visitor")
